name: Deploy infrastructure, build app, deploy app

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log Level'
        required: true
        default: 'warning'

permissions:
      id-token: write
      contents: read


jobs:
  build:
    name: xyz
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1