name: Build Logic App

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log Level'
        required: true
        default: 'warning'

jobs:
  build:
    name: Build LogicApp Demo
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Package
      run: (cd src/LogicAppsStandardDemo; mkdir -p ../../output; zip -r ../../output/workflow.zip .)
    - name: Upload Package
      uses: actions/upload-artifact@v2
      with:
        name: workflow
        path: ./output/
        retention-days: 1

  deploy-dev:
    name: 'Deploy in Dev'
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: 'Az CLI Login'
      uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

 #   - name: get deployment package
 #     uses: actions/download-artifact@master
 #     with:
 #       name: workflow
 #       path: ./output/
