name: Build and deploy application

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log Level'
        required: true
        default: 'warning'
        
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

permissions:
      id-token: write
      contents: read

jobs:
  build:
    name: Build LogicApp Demo
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v1
    - name: Package
      run: (cd src/LogicAppsStandardDemo; mkdir -p ../../output; zip -r ../../output/workflow.zip .)
    - name: 'Upload Package'
      uses: actions/upload-artifact@v2
      with:
        name: workflow
        path: ./output/
        retention-days: 1

  Deploy:
      runs-on: ubuntu-latest
      environment: ${{ github.event.inputs.environment }}
      steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'get deployment package'
        uses: actions/download-artifact@master
        with:
          name: workflow
          path: ./output/

      - run: |
          echo "Azure Region: ${{vars.AZURE_REGION}}"
          echo "LogicApp Plan Name: ${{vars.LOGICAPPPLAN_NAME}}"
          echo "LogicApp Name: ${{vars.LOGICAPP_NAME}} "
          echo "Workload Environment: ${{vars.WORKLOAD_ENVIRONMENT}}"

      - name: 'Deploy LogicApp with Functions Action'
        uses: Azure/functions-action@v1
        id: la
        with:
          app-name: ${{ vars.LOGICAPP_NAME }}
          package: ./output/workflow.zip
          
      - name: 'update logicapp settings'
        uses: azure/appservice-settings@v1
        with:
          app-name: ${{ vars.LOGICAPP_NAME }}
          app-settings-json: '[{"name":"testappsetting","value":"testappsettingvalue","slotSetting":"false"}]'
          connection-strings-json: '[{"name":"testconnstr","value":"testconnstrvalue", "type":"Custom", "slotSetting":"false"}]'
          #Note: can also use general-settings-json to manage workflow and general settings



