name: Deploy infrastructure, build app, deploy app

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: 'environment to run on'
        required: true
        default: 'development'

permissions:
      id-token: write
      contents: read

jobs:
  call-infra-deployment-workflow-in-local-repo:
    uses: ./.github/workflows/deploy-infrastructure.yml
    with:
      environment: ${{ inputs.environment }}
    secrets: inherit
    
  call-app-deployment-workflow-in-local-repo:
    needs: call-infra-deployment-workflow-in-local-repo       # need to have the infra deploy first and not deploy the app if there is an issue
    uses: ./.github/workflows/deploy-application.yml
    with:
      environment: ${{ inputs.environment }}
    secrets: inherit