name: Deploy infrastructure, build app, deploy app

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log Level'
        required: true
        default: 'warning'

permissions:
      id-token: write
      contents: read

jobs:
  call-app-deployment-workflow-in-local-repo:
    uses: ./.github/workflows/deploy-application.yml