name: Build and deploy application

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log Level'
        required: true
        default: 'warning'

permissions:
      id-token: write
      contents: read


jobs:
  build:
    name: Build LogicApp Demo
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v1
    - name: Package
      run: (cd src/LogicAppsStandardDemo; mkdir -p ../../output; zip -r ../../output/workflow.zip .)
    - name: 'Upload Package'
      uses: actions/upload-artifact@v2
      with:
        name: workflow
        path: ./output/
        retention-days: 1

  Deploy:
      runs-on: ubuntu-latest
      steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'get deployment package'
        uses: actions/download-artifact@master
        with:
          name: workflow
          path: ./output/

      - name: 'update logicapp settings'
        uses: azure/appservice-settings@v1
        with:
          app-name: logicappdeploymentdemo
          app-settings-json: '[{"name":"testappsetting","value":"testappsettingvalue","slotSetting":"false"}]'
          connection-strings-json: '[{"name":"testconnstr","value":"testconnstrvalue", "type":"other", "slotSetting":"false"}]'

      - name: 'Deploy LogicApp with Functions Action'
        uses: Azure/functions-action@v1
        id: la
        with:
          app-name: logicappdeploymentdemo
          package: ./output/workflow.zip

