name: Deploy Infrastructure

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log Level'
        required: true
        default: 'warning'

  workflow_call:

permissions:
      id-token: write
      contents: read


jobs:
  deployInfra:
    name: 'deploy infrastructure'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: 'deploy bicep template'
      uses: Azure/arm-deploy@1.0.9
      id: deploy
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        template: ./src/infrastructure/main.bicep
        parameters: 'environment=dev location=eastus'   # Can also specify a parameters file location.  Wiwll want to have both of these driven from environment variables
        deploymentMode: Incremental
        deploymentName: lgdemodeployment
        failOnStdErr: false


    #Will need to update environment variables with this info
    - run: echo ${{ steps.deploy.outputs.LogicAppPlan_name }}
    - run: echo ${{ steps.deploy.outputs.LogicApp_name}}
    - run: echo ${{ steps.deploy.outputs.LogicApp_Storage_name }}
    - run: echo ${{ steps.deploy.outputs.ResourceGroupName }}
