name: Deploy Infrastructure

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log Level'
        required: true
        default: 'warning'

  workflow_call:

permissions:
      id-token: write
      contents: write
    
jobs:
  deployInfra:
    name: 'deploy infrastructure'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy Azure Resource Manager (ARM) Template
      uses: Azure/arm-deploy@v1.0.9
      id: deploy
      with:
        scope: subscription
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        template: ./src/infrastructure/main.bicep
        deploymentMode: Incremental
        deploymentName: ${git_branch}.${git_hash}            # pickup the commit id for the deployment name
        region: ${{vars.AZURE_REGION}}                                 # Want this driven from an environment variable
        parameters: 'environment=${{vars.WORKLOAD_ENVIRONMENT}} location=${{vars.AZURE_REGION}}'  # Can also specify a parameters file location.  Want these driven from environment variables
        failOnStdErr: false

    #Will need to update environment variables with this info
    - run: |
        echo "LogicAppPlan_name: ${{ steps.deploy.outputs.LogicAppPlan_name }}"
        echo "LogicApp_name: ${{ steps.deploy.outputs.LogicApp_name}}"
        echo "LogicApp_Storage_name: ${{ steps.deploy.outputs.LogicApp_Storage_name }}"
        echo "ResourceGroupName: ${{ steps.deploy.outputs.ResourceGroupName }}"

    #Update variables with outputs, these will be used by the app deployment script.
    #this approach is cumbersome, couldn't find another way to update a variable... suggestions welcome
    #NOTE: Had to create a PAT with the correct permissions to write a variable, this works but it will expire eventually and break the workflow
    #      the error will mention that it can't do integration operations or something...basically a 403
    #Alternatives
    # - Read and write a parameter file to the repo
    # - Use Keyvault or Azure App Config
    - run: |
        gh api --method PATCH -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/karlrissland/Logic-App-Standard-Deployment/actions/variables/RESOURCEGROUPNAME -f name='RESOURCEGROUPNAME' -f value=${{ steps.deploy.outputs.ResourceGroupName }}
        gh api --method PATCH -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/karlrissland/Logic-App-Standard-Deployment/actions/variables/LOGICAPPPLAN_NAME -f name='LOGICAPPPLAN_NAME' -f value=${{ steps.deploy.outputs.LogicAppPlan_name }}
        gh api --method PATCH -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/karlrissland/Logic-App-Standard-Deployment/actions/variables/LOGICAPP_NAME -f name='LOGICAPP_NAME' -f value=${{ steps.deploy.outputs.LogicApp_name}}
      env:
        GH_TOKEN: ${{ secrets.GH_PAT }}  
