name: Deploy Infrastructure

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log Level'
        required: true
        default: 'warning'

permissions:
      id-token: write
      contents: read


jobs:
  build: