name: Test Azure Login
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

permissions:
      id-token: write
      contents: read
      
jobs: 
  Windows-latest:
      runs-on: windows-latest
      steps:
        - name: OIDC Login to Azure Public Cloud with AzPowershell (enableAzPSSession true)
          uses: azure/login@v1
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
            enable-AzPSSession: true

        - name: 'Get resource group with PowerShell action'
          uses: azure/powershell@v1
          with:
             inlineScript: |
               Get-AzResourceGroup
             azPSVersion: "latest"

        - name: Test GH PAT Token
          uses: actions/checkout@v2
          - id: repo-basename
            run: |
              echo "value='basename ${{ github.repository }}'" >> $GITHUB_OUTPUT
            shell: bash
          with:
            #repository: ${{ github.event.repository.name }}
            repository: ${{ github.repository }}
            token: ${{ secrets.GH_PAT }}

  Linux-latest:
      runs-on: ubuntu-latest
      steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      - name: 'Run Azure CLI Commands'
        run: |
          az account show
          az group list
          pwd
